- hosts: vmtest
  sudo: yes
  roles:
    - icu
    - mumble-server
    # - { role: "rbenv", env: "system", ruby_version: "2.1.0-preview1"}
    # - rbenv_plugins:
    #   - { name: "rbenv-vars", repo: "git://github.com/sstephenson/rbenv-vars.git", version: "v1.2.0" }
    #   - { name: "ruby-build", repo: "git://github.com/sstephenson/ruby-build.git", version: "v20131225.1" }
    #   - { name: "rbenv-default-gems", repo: "git://github.com/sstephenson/rbenv-default-gems.git", version: "v1.0.0" }
    #   - { name: "rbenv-installer", repo: "git://github.com/fesplugas/rbenv-installer.git", version: "8bb9d34d01f78bd22e461038e887d6171706e1ba" }
    #   - { name: "rbenv-update", repo: "git://github.com/rkh/rbenv-update.git", version: "32218db487dca7084f0e1954d613927a74bc6f2d" }
    #   - { name: "rbenv-whatis", repo: "git://github.com/rkh/rbenv-whatis.git", version: "v1.0.0" }
    #   - { name: "rbenv-use", repo: "git://github.com/rkh/rbenv-use.git", version: "v1.0.0" }