---
- name: Install rmi dependencies
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - bison
    - openssl
    - libreadline5
    - libreadline-dev
    - curl
    - git-core
    - zlib1g
    - zlib1g-dev
    - libssl-dev
    - libsqlite3-0
    - libsqlite3-dev
    - sqlite3
    - libxml2-dev
    - subversion
    - autoconf
