---
- name: Install Transmission
  apt: name=transmission-daemon state=present

- name: Make sure transmission is not running
  service: name=transmission-daemon state=stopped
  ignore_errors: true

- name: Add user 
  user: name={{trans_user}} group=sshusers password={{trans_pswd}}

- name: Add downloads folder
  file: path=/home/{{trans_user}}/downloads owner={{trans_user}} group=sshusers state=directory

- name: Add torrents folder
  file: path=/home/{{trans_user}}/torrents owner={{trans_user}} group=sshusers state=directory

- name: Change downloads folder mode
  command: chmod 777 /home/{{trans_user}}/downloads

- name: Copy Transmission configuration
  template: 
    src=settings.json
    dest=/var/lib/transmission-daemon/info/settings.json

- name: Make sur transmission is started
  service: name=transmission-daemon state=started
  ignore_errors: true