- name: Install mysql-server
  action: apt name=mysql-server
  notify:
    - mysql_secure_installation

- name: Install libmysqlclient-dev
  apt: name=libmysqlclient-dev state=present

- name: Write conf.d/mysqld.cnf
  action: template src=mysqld.cnf dest=/etc/mysql/conf.d/mysqld.cnf
  notify:
    - restart mysql

- name: Write conf.d/client.cnf
  action: template src=client.cnf dest=/etc/mysql/conf.d/client.cnf
  notify:
    - restart mysql